---

- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone }}"

- name: set drop as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=drop
  when: default_zone != "drop"
  notify: reload firewalld

- name: deny all incomming

- name: drop all incomming traffic
  firewalld:
    zone: drop 
    immediate: yes
    permanent: yes
  notify: reload firewalld
...
