---

- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone.stdout }}"

- name: add permitted networks to home zone
  firewalld:
    zone: home
    state: enabled
    source: "{{ item }}"
    immediate: yes
    permanent: yes
  tags: firewall
  notify: reload firewalld
  with_items: " {{ home_networks }}"

- name: add ssh port to home zone
  firewalld:
    zone: home
    service: ssh
    state: enabled
    immediate: yes
    permanent: yes
  tags: firewall
  notify: reload firewalld

- name: remove ssh from public
  firewalld:
    zone: public
    service: ssh
    state: disabled
    immediate: yes
    permanent: yes
  tags: firewall
  notify: reload firewalld

- name: set block as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=block
  tags: firewall
  when: default_zone.stdout != "block"
...
