---
- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone }}"

- name: set drop as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=drop
  when: default_zone != "drop"
  notify: restart firewalld

- name: disable home zone
  firewalld:
    zone: home
    state: disabled
    permanent: yes
    immediate: yes
  tags: hardening
  notify: restart firewalld

- name: disable thedeep zone
  firewalld:
    zone: thedeep
    state: disabled
    permanent: yes
    immediate: yes
  tags: hardening
  notify: restart firewalld
...
