---


- hosts: dns
  user: pi
  roles:
    - common
    - dns

      #- hosts: goo
      #  user: greatoldone
      #  roles:
      #    - common
      #    - deep

- hosts: media
  user: greatoldone
  roles:
    - common
    - media

