---
- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone
  tags: dns-firewall

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone.stdout }}"
  tags: dns-firewall

- name: create dns firewall zone
  firewalld:
    zone: dns 
    state: present 
    permanent: yes
  tags: dns-firewall
  become: yes
  notify: restart firewalld

- name: Flush handlers 
  meta: flush_handlers
  tags: dns-firewall

- name: add dns udp port to dns zone
  firewalld:
    port: 53/udp
    zone: dns 
    state: enabled
    immediate: yes
    permanent: yes
  tags: dns-firewall
  become: yes
  notify: restart firewalld

- name: add dns tcp port to dns zone
  firewalld:
    port: 53/tcp
    zone: dns 
    state: enabled
    immediate: yes
    permanent: yes
  tags: dns-firewall
  notify: restart firewalld
  become: yes

- name: add ssh port to dns zone
  firewalld:
    port: 22/tcp
    zone: dns 
    state: enabled
    immediate: yes
    permanent: yes
  tags: dns-firewall
  notify: restart firewalld
  become: yes

- name: disable home zone for dns
  firewalld:
    zone: home 
    state: disabled
    permanent: yes
    immediate: yes
  tags: dns-firewall
  notify: restart firewalld

- name: set dns as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=dns
  tags: dns-firewall
  when: default_zone.stdout != "dns"
  notify: restart firewalld
  become: yes

...
