---
- name: restart ssh
  systemd:
    name: sshd
    daemon_reload: yes
    state: restarted

- name: restart firewalld
  systemd:
    name: firewalld
    daemon_reload: yes
    state: restarted 

...
