---
- name: Restart sshd
  ansible.builtin.systemd:
    name: sshd
    daemon_reload: true
    state: restarted
  become: true

- name: Start firewalld
  ansible.builtin.systemd:
    name: firewalld
    daemon_reload: true
    state: started
  become: true

- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    daemon_reload: true
    state: restarted
  become: true

...
