---
- name: Make sure we have a 'greatoldone' group.
  group:
    name: "greatoldone"
    state: present

- name: create greatoldone group.
  group:
    name: "greatoldone"
    state: present

- name: create greatoldone user.
  user:
    name: "greatoldone"
    groups: "greatoldone"
    shell: /bin/bash
    home: /home/greatoldone
    create_home: yes
    state: present
  tags: users

- name: Allow 'greatoldone' group passwordless sudo.
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^%greatoldone'
    line: '%greatoldone ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s 
  tags: users

- name: password authentication not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config 
    state: present
    backup: yes
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  tags: users
  notify:
    - restart ssh 

- name: ssh as root not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  tags: users
  notify:
    - restart ssh 

- name: copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    owner: root
    mode: '0644'
    backup: yes

- name: Add ssh key to 'greatoldone'.
  authorized_key:
    user: greatoldone
    state: present
    key: ssh_keys.goo_key
      #key: '{{ goo_key }}'
      #with_items: "{{ goo_key }}"
  tags: users
...
