---
- name: create greatoldone user.
  user:
    name: "greatoldone"
      #groups: "greatoldone"
    shell: /bin/bash
    home: /home/greatoldone
    create_home: yes
    state: present
  tags: users
  become: yes

# update to use sudoers
- name: Allow 'greatoldone' group passwordless sudo.
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^%greatoldone'
    line: '%greatoldone ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s 
  tags: users
  become: yes

- name: password authentication not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config 
    state: present
    backup: yes
    line: 'PasswordAuthentication no'
  tags: ssh 
  become: yes
  notify:
    - restart ssh 

- name: password authentication not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config 
    state: absent
    backup: yes
    line: 'PasswordAuthentication yes'
  tags: ssh 
  become: yes
  notify:
    - restart ssh 

- name: ssh as root not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    line: 'PermitRootLogin no'
  tags: ssh
  become: yes
  notify:
    - restart ssh 
    
- name: ssh as root not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: absent
    line: 'PermitRootLogin yes'
  tags: ssh
  become: yes
  notify:
    - restart ssh 

      #- name: copy hosts file
      #  copy:
      #    src: #hosts
      #    dest: /etc/hosts
      #    owner: root
      #    mode: '0644'
      #    backup: yes
      #  tags: hosts

- name: Add ssh key to 'greatoldone'.
  authorized_key:
    user: greatoldone
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys.goo_key }}"
  tags: users
  become: yes

- name: install relevant packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: packages
  become: yes
  ignore_errors: yes
  notify: start firewalld

- name: Flush handlers 
  meta: flush_handlers
  tags: packages

- name: create thedeep firewall zone
  firewalld:
    zone: thedeep
    state: present 
    permanent: yes
  tags: firewall
  become: yes
  notify: restart firewalld

- name: Flush handlers 
  meta: flush_handlers
  tags: firewall

- name: add source to thedeep
  firewalld:
    source: 192.168.50.244
    zone: thedeep
    state: enabled
    immediate: yes
    permanent: yes
  tags: firewall
  become: yes
  notify: restart firewalld

- name: add ssh port for thedeep
  firewalld:
    zone: thedeep
    service: ssh
    state: enabled
    immediate: yes
    permanent: yes
  tags: firewall
  become: yes
  notify: restart firewalld

...
