---
#- name: Make sure we have a 'greatoldone' group.
#  group:
#    name: "greatoldone"
#    state: present

      #- name: create greatoldone group.
      #  group:
      #    name: "greatoldone"
      #    state: present
      #  become: yes

- name: create greatoldone user.
  user:
    name: "greatoldone"
      #groups: "greatoldone"
    shell: /bin/bash
    home: /home/greatoldone
    create_home: yes
    state: present
  tags: users
  become: yes

- name: Allow 'greatoldone' group passwordless sudo.
  lineinfile:
    dest: /etc/sudoers
    state: present
    backup: yes
    regexp: '^%greatoldone'
    line: '%greatoldone ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s 
  tags: users
  become: yes

- name: password authentication not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config 
    state: present
    backup: yes
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
  tags: ssh 
  become: yes
  notify:
    - restart ssh 

- name: ssh as root not allowed.
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
  tags: ssh
  notify:
    - restart ssh 

#maybe ignore this
#- name: SSH only on port 1984
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    state: present
#    regexp: '^#Port 22'
#    line: 'Port 1984'
#  tags: ssh
#  notify:
#    - restart ssh

- name: copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    mode: '0644'
    backup: yes

- name: Add ssh key to 'greatoldone'.
  authorized_key:
    user: greatoldone
    state: present
    key: "{{ item }}"
  with_items: "{{ ssh_keys.goo_key }}"
  tags: users

- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone
  tags: firewall

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone }}"
  tags: firewall

- name: create thedeep firewall zone
  firewalld:
    zone: thedeep
    state: present 
    permanent: yes
  tags: firewall
  notify: restart firewalld

- name: Flush handlers 
  meta: flush_handlers
  tags: firewall

- name: add source to thedeep
  firewalld:
    source: 192.168.50.244
    zone: thedeep
    state: enabled
    immediate: yes
    permanent: yes
  tags: firewall
  notify: restart firewalld

- name: add ssh port for thedeep
  firewalld:
    zone: thedeep
    port: 1984/tcp
    state: enabled
    immediate: yes
    permanent: yes
  tags: firewall
  notify: restart firewalld

- name: enable home zone
  firewalld:
    port: 1984/tcp
    zone: home
    state: enabled
    permanent: yes
    immediate: yes
  tags: firewall
  notify: restart firewalld
    
#this should cover for SFTP sa well since it is ssh ftp.
#- name: add ssh service from goo to firewall
#  firewalld:
#    zone: home
#    service: ssh
#      #    port: 1984/tcp
#    state: enabled
#    immediate: yes
#    permanent: yes
#  tags: firewall
#  notify: restart firewalld

#- name: add nsf service to firewall
#  firewalld:
#    zone: home
#    service: nsf
#    port: 2049
#    state: enabled
#    immediate: yes
#    permanent: yes
#  tags: firewall
#  notify: reload firewall

#- name: add media server ports

- name: set block as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=block
  tags: firewall
  when: default_zone != "block"
  notify: restart firewalld

- name: install relevant apt packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  tags: packages

...
