---
- name: register current default zone 
  command: firewall-cmd --get-default-zone
  register: default_zone
  tags: firewall

- name: print default zone
  debug:
    msg: "default zone is: {{ default_zone.stdout }}"
  tags: firewall

- name: set block as default zone in firewalld if not set
  command: firewall-cmd --set-default-zone=block
  tags: firewall
  when: default_zone.stdout != "block"
  notify: restart firewalld
  become: yes 


...
