---
#add ssh keys required for goo
ssh_keys:
  goo_key: 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9G0YpI6HymB8Fs0NSnz69ixqrYkbSKQFWIgahEwZ2TqalyF9JWzFn5OJLk8Q3y6iGaKo7lKTYPSLe+F1wazgy9ugdfioRPvacBUBaISF96M7ZEnfnDaUTLXpeXdMvrAIiQ6vj1sUds/EDEzWEvm+hFBc4cV/EcjQb1H6B+QFV85cLnuVRdHng0V5NO0YRsde+9k0W4koFbzEnMbMz7W5gdJBYVveZawmi0LxOFBTTxNDPT6hcaUzxGDvGYfWYSJatWd9JA6RsUWMqo9LCm7i5+i45/EjKdnzrbGjmYEEvsrLUGJhoUgm49BuuYNf/Yy+ah7t15lwWVOjWv+WRh/pC9rwhmNNv8QZGaztKlFJncoxUHG3HLWOUAPizxFu4WUm5DSLivoMCaRJT01bgmrLG+TsV0vyzDhyDE5FJMBA0myJ1/HS/2262OPBdGgBbytl45CyHkM4u3cYhGOpNAyQp5QCoEX6xmoHk2tYMoOeXDUhrL+KzJSKf2zZk7V8pMPZukaK7xpo7cbsI6zd0BtZaP4cF/8tdd1LY1FVOCuEgbqRQ5ohdKk6WuHW3Y8GAzwURL5qeVufTJIKiB5nwdSoabxcLehH24QndpFSZtBr4xB0nHDmG9JUhJD2UDqYnyVpVn+nWFwKt546m5qlyFXEOEHDX+Ar8Nb3YmMftGpWVWQ== Oscar@fedora
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDCmy4yE8rtzivckCbNRjGFjaOT8eJQuAATyd0iuKxadi0B/7Nz2ylITplE52TfFilsZg4Z5t2wOJ+Ursm70e0060PsaQ5rpxHG6+0Jhy6vlTnsQ+CdhgXRxV3WT5RJpMA/cjGnh8oZS6fN4ESe3aJH81qEzRcB7pEyUk/dISOFjRhlfqw344PEIRcUi3HctAnwW+yJ0OJuw1otUve+WhAR1DdJ3556QR9+sfZA7+9/PKQbgGy/ebGJfPI9lDCoxyL68eyYPUJqaXAIYM8whyCKgmErNUYXRvD7jNlHifXtCWSofeQfg3qQZmj5hswd8Z1I6b1yGU6NsxkXy8YK7LEyj4kE6rgIpCG6PuJ1AL2Ni2tJqVy4eSyOO614H7mBQh9ZeCmH6e1EMLzmwFdBfcsKFTte+//jvzHd917Uzd949fR29KMgj7S6OQ05qvxYTKJV8otPv5Irrt4XROCqvGLrWRGDImiQ2W1DH2uk2DmPbQgDNpDnVac29eWVlfOhh8Wpls0+JTQlNNuOru04CFb2WsKAamaxFq+xUegf7auKTDy19OaRW2eVu+qujvz26XI9kSQVqMDBW7phbOhtUydqMq80gO+ytEy9zd8pjctUdyHrVi+44yk9EEgpImXY97Kr6Mbfq40TuKuH9HDo+7Crod7FYHf03HV3/uYV99tHvw== killerrabbit@Achenar

# add packages you wish to install.
packages:
  - htop
  - nmap
  - traceroute  
  - curl
    #- telnet
  - nc
  - neofetch
  - dnsutils
  - bind-utils
  - vim
  - tree
  - firewalld
  - audit
  - git
  - golang
  - python
...
