---
#add ssh keys required for goo
ssh_keys:
  goo_key: 
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9G0YpI6HymB8Fs0NSnz69ixqrYkbSKQFWIgahEwZ2TqalyF9JWzFn5OJLk8Q3y6iGaKo7lKTYPSLe+F1wazgy9ugdfioRPvacBUBaISF96M7ZEnfnDaUTLXpeXdMvrAIiQ6vj1sUds/EDEzWEvm+hFBc4cV/EcjQb1H6B+QFV85cLnuVRdHng0V5NO0YRsde+9k0W4koFbzEnMbMz7W5gdJBYVveZawmi0LxOFBTTxNDPT6hcaUzxGDvGYfWYSJatWd9JA6RsUWMqo9LCm7i5+i45/EjKdnzrbGjmYEEvsrLUGJhoUgm49BuuYNf/Yy+ah7t15lwWVOjWv+WRh/pC9rwhmNNv8QZGaztKlFJncoxUHG3HLWOUAPizxFu4WUm5DSLivoMCaRJT01bgmrLG+TsV0vyzDhyDE5FJMBA0myJ1/HS/2262OPBdGgBbytl45CyHkM4u3cYhGOpNAyQp5QCoEX6xmoHk2tYMoOeXDUhrL+KzJSKf2zZk7V8pMPZukaK7xpo7cbsI6zd0BtZaP4cF/8tdd1LY1FVOCuEgbqRQ5ohdKk6WuHW3Y8GAzwURL5qeVufTJIKiB5nwdSoabxcLehH24QndpFSZtBr4xB0nHDmG9JUhJD2UDqYnyVpVn+nWFwKt546m5qlyFXEOEHDX+Ar8Nb3YmMftGpWVWQ== Oscar@fedora
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCsiYNSUKpSyk5D9OUukyMkkv6IfJ5RamFgQCTn1pqyFMxFKLYc16GuCsZ+qdxGxICVCW3NsUnZJwXRYAHJHLzN9J0iASlQ9nz6jsxVkeCR1Tr2ExSUftKlnWgDNdRz/cOkXYQQ+WJIOr5JhJY8WmW1ZDjWnpCVs7Hb8TlBYCk863NCIs2MGbYpBDN/DSjFL26aLNynymKJpEe5zNUPb3kXhYlZgqr2IbXlBh/8Ujsg2u2jo+JmrE3xWMfE9kiL/x+YkHv9Pa2XV1o8QkKhjyTUO8S7w4zQxbruNFGltCAe6ne2HcQjcRu8kV+K44XmOssKfsfQaLZUXnEZ3jzJSJIBeESa6FxL+plrNRmudPqwg39wDn6Hqvpz3wUi/9mGWKgNavpRd7QYdV09tXECVyt9HUJaSLjrexBUEl980i1Y7QkH6vYcuGwhFehHixl7HWK7MbEu0va+6XzPby2Tl42i4xfR8DYjF3CoGRExH4yozkm4bQoNp8BQH4GL0RD2R/hTW0Q5IUkKr7KWO/LUrtlz261JB53GG0/C1BP3ggWW2ek9fxJVbJyqhXtcGZWOzAh+Usu6m3gk353Y+CGUVRPQhjYQC3spJbrKDj94q9eRt8Y6BGfLhM70Zt7Lo9F16Lq4/6a6AL4yHtRrON9iJFC1KN1lqE5X/zcHZIQUhEQfvw== killerrabbit@AchenarIII


hosts:
  - 192.168.50.42 pi-hole
  - 192.168.50.51 polaris 

# add packages you wish to install.
packages:
  - htop
  - nmap
  - traceroute  
  - curl
    #- telnet
  - neofetch
  - dnsutils
  - vim
  - tree
  - firewalld
  - audit
  - git
  - python
  - pam_yubico
  - yubikey_manager
...
